default: &default
  adapter: postgresql

development:
  <<: *default
  database: gofish_development

test:
  <<: *default
  database: gofish_test

production:
  <<: *default
  database: gofish_production
